### PR TITLE
Move constructor code into check

### LINKED ISSUE #28: SecurityAdvisory does "work" in the constructor
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 1.10.0

#### Summary

https://github.com/laminas/laminas-diagnostics/pull/16 added code does work in `SecurityAdvisory::__construct()` that causes temporary files to be created. Related: https://github.com/liip/LiipMonitorBundle/issues/261.

Ping @paras-malhotra.

### PR DESCRIPTION
**Pull request by lostfocus**
|    Q          |   A
|-------------- | ------
| Bugfix        | yes

This moves the instantiation of the AdvisoryAnalyzer into the check function to make sure we only download the advisories when actually checking them. 
Closes #28

### CODE REVIEW

File: src/Check/SecurityAdvisory.php [hunk 1]
```diff
@@ -22,9 +22,9 @@ class SecurityAdvisory extends AbstractCheck
     protected $lockFilePath;
 
     /**
-     * @var \Enlightn\SecurityChecker\AdvisoryAnalyzer
+     * @var \Enlightn\SecurityChecker\AdvisoryAnalyzer|null
      */
-    protected $advisoryAnalyzer;
+    protected $advisoryAnalyzer = null;
```
Comment (Ocramius) [inline src/Check/SecurityAdvisory.php:27]: Do we need this state at all now? In theory, it can be a local variable, right?

File: src/Check/SecurityAdvisory.php [hunk 2]
```diff
@@ -56,14 +56,16 @@ public function __construct($lockFilePath = null)
...
         $this->lockFilePath    = $lockFilePath;
-
-        $parser = new AdvisoryParser((new AdvisoryFetcher)->fetchAdvisories());
-
-        $this->advisoryAnalyzer = new AdvisoryAnalyzer($parser->getAdvisories());
     }
 
     public function check()
     {
+        if ($this->advisoryAnalyzer === null) {
```
Comment (Ocramius) [inline src/Check/SecurityAdvisory.php:66]: Is there any meaningful way to test this behavior, perhaps? Maybe instantiate the `SecurityAdvisory` class with a `$lockFilePath` that contains invalid JSON?

**Review by Ocramius — CHANGES_REQUESTED** [review]

File: src/Check/SecurityAdvisory.php (hunk 1 above)
Comment (lostfocus) [reply src/Check/SecurityAdvisory.php:27]: Yeah, I thought about it - but in this way the class can still be extended by this class with a setter: https://github.com/laminas/laminas-diagnostics/blob/1.11.x/test/TestAsset/Check/SecurityAdvisory.php to keep the tests here https://github.com/laminas/laminas-diagnostics/blob/1.11.x/test/ChecksTest.php#L558 valid.

File: src/Check/SecurityAdvisory.php (hunk 2 above)
Comment (lostfocus) [reply src/Check/SecurityAdvisory.php:66]: Okay, I'm a bit lost, to be honest. I kept the AdvisoryAnalyzer as a class property to make sure the current tests keep running.

Comment (Ocramius) [reply src/Check/SecurityAdvisory.php:66]: #28 reports a **problem**.

What we need to do, to prevent future regressions, is to reproduce said problem, and verify that it doesn't occur.

In practice, in the test:

```
$check = new SecurityAdvisory(...);

$this->expectException(...);

$advisory->check();
```

Comment (lostfocus) [reply src/Check/SecurityAdvisory.php:66]: Okay, but in the end that's impossible without refactoring the while SecurityAdvisory class and wrapping some dependency injection magic around it, isn't it? What needs to be proven/tested is that there is no http call in the SecurityAdvisory constructor and it is outside of my knowledge on how to prove the absence of that behaviour. 
  
I did add a test for the exception we saw in production - not sure how helpful it is. 

In the end the transfer of the `fetchAdvisories` function from the constructor into the `check` function is just fighting symptoms anyway.
The real problem happens here: https://github.com/enlightn/security-checker/blob/main/src/Filesystem.php#L21 where somehow between line 21 and 25 the directory vanishes. "Somehow" in this case was because multiple instances of the SecurityAdvisory class were being created who all wrote to and deleted from the temporary directory. And the only way to solve _that_ problem is probably some kind of locking mechanism on the OS level.

Comment (Ocramius) [reply src/Check/SecurityAdvisory.php:66]: > Okay, but in the end that's impossible without refactoring the while SecurityAdvisory class and wrapping some dependency injection magic around it, isn't it?

No, if you create a `new SecurityAdvisory()` with an invalid lock file, it should crash as per `1.11.x`.

With your patch, it should crash when you call `->check()`.

Comment (lostfocus) [reply src/Check/SecurityAdvisory.php:66]: Not really? The check against the lock file is happening in `->check()` already and that's not something that I changed.  
That's not the problem here - the problem is the `(new AdvisoryFetcher)->fetchAdvisories()` in the constructor which triggered a download of the advisories when the Symfony dependency injection creates a `SecurityAdvisory` object even without the intention to run the check method.

Comment (Ocramius) [reply src/Check/SecurityAdvisory.php:66]: Ah, I see, sorry, I misread that, my bad!

Indeed, there is hidden I/O that is hard to "fake" or "block", which means that testing will provide tricky :-\

Comment (lostfocus) [reply src/Check/SecurityAdvisory.php:66]: So, once again I'm a bit stumped. As far as I can tell it now works as intended, but I'm not sure how to test the whole thing. Couldn't really think of a good solution in the last week, either.

Comment (Ocramius) [reply src/Check/SecurityAdvisory.php:66]: Yeah, let's just roll with the change as-is :+1: 

In practice, the issue here is that `AdvisoryFetcher` relies on global state, so a proper fix would go up the chain.

Comment (Ocramius) [reply src/Check/SecurityAdvisory.php:66]: The only thing I'd say we should get rid of, before merging, is to get rid of `$this->advisoryFetcher`, and instead always instantiate a new one in the `->check()` method.

**Comment by Ocramius** [comment]
@lostfocus since this is a bugfix, I'm thinking this could go against `1.10.x`, right?

File: src/Check/SecurityAdvisory.php (hunk 2 above)
Comment (lostfocus) [reply src/Check/SecurityAdvisory.php:66]: Yeah, you're absolutely right. I added this for a test that basically doesn't really test anything worth testing. I'm removing the AdvisoryFetcher and the test that used it.

Comment (lostfocus) [reply src/Check/SecurityAdvisory.php:66]: So, here go.

Comment (Ocramius) [reply src/Check/SecurityAdvisory.php:66]: I still see the property?

Comment (lostfocus) [reply src/Check/SecurityAdvisory.php:66]: That's the analyzer, not the fetcher. There are a bunch of tests using the analyzer.

Comment (Ocramius) [reply src/Check/SecurityAdvisory.php:66]: Yes, and now it's nullable - shouldn't the property just go away?

Comment (lostfocus) [reply src/Check/SecurityAdvisory.php:66]: If you have a good idea how to run these tests: https://github.com/laminas/laminas-diagnostics/blob/1.10.x/test/ChecksTest.php#L558 without the property, I'd be happy to remove it, too.

Comment (Ocramius) [reply src/Check/SecurityAdvisory.php:66]: I've re-read all my comments: gonna dismiss them as my own brainfart, sorry for all the noise 😬

**Review by Ocramius — APPROVED** [review]

**Comment by Ocramius** [comment]
Thanks @lostfocus - sorry for the long delay
